In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing",arr[2:7])
print(" with step",arr[1:8:2])
print("Negative Indexing",arr[-3])


Basic Slicing [3 4 5 6 7]
 with step [2 4 6 8]
Negative Indexing 7


In [5]:
arr_2d = np.array([[1,2,3],
[4,5,6],
[7,8,9]])

print("SPecific Element",arr_2d[1,2])
print("Entire row:",arr_2d[1])
print("ENtire row:",arr_2d[:,1])

SPecific Element 6
Entire row: [4 5 6]
ENtire row: [2 5 8]


Sorting

In [6]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted Array",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column",np.sort(arr_2d_unsorted,
axis = 1))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


## filter

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 ==0]
print("Even numbers", even_numbers)

Even numbers [ 2  4  6  8 10]


## filter with mask

In [8]:
mask = numbers > 5
print("Numbers greater than 5",numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## fancy indexing vs np.where()

In [9]:
indices = [0,2,4]
print(numbers[indices])
where_result = np.where(numbers>5)
print(where_result)
print("NP where",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [10]:
condition_array = np.where(numbers>5,numbers*4,numbers)
print(condition_array)


[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [12]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))

print(combined)

[1 2 3 4 5 6]


### array compatibility

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("compatibility shapes",a.shape == b.shape)

compatibility shapes False


In [17]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))

print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print("with new col",with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new col [[1 2 7]
 [3 4 8]]


## delete

In [20]:
arr = np.array([1,2,3,4,5])

deleted = np.delete(arr,2)
print("Array after deletion",deleted)

Array after deletion [1 2 4 5]
