## Numpy array and basics 
learn about numpy with chai aur code

In [3]:
import numpy as np


### creating arrow from list 

In [7]:
arr_1d = np.array([1,2,3,4,5])
print("1D array:",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2d)

1D array: [1 2 3 4 5]
2D array: [[1 2 3]
 [4 5 6]]


In [10]:
py_list = [1,2,3]
print("Python list multiplication",py_list *2)

np_array = np.array([1,2,3]) #element wise multiplicaton 
print("Python list multiplication",np_array *2)

import time 

start = time.time()
py_list = [i*2 for i in range (100000)]
print("\n List operation tme:",time.time()-start)

start = time.time()
np_array= np.arange(100000)*2
print("\n Numpy operation time  operation:",time.time()-start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python list multiplication [2 4 6]

 List operation tme: 0.005910634994506836

 Numpy operation time  operation: 0.001710653305053711


creating array from scratch

In [11]:
zeros = np.zeros((3,4))
print("zeros array:\n",zeros)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
ones = np.ones((2,3))
print("ones array:\n",ones)

ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
full = np.full((2,2),7)
print("full array:\n",full)

full array:
 [[7 7]
 [7 7]]


In [14]:
random = np.random.random((2,3))
print("random array:\n",random)

random array:
 [[0.00862367 0.10819909 0.67460988]
 [0.10018762 0.78961498 0.39130283]]


In [15]:
sequence = np.arange(0,10,2)
print("sequqnce array:\n",sequence)

sequqnce array:
 [0 2 4 6 8]


## vector matrix and tensor


In [18]:
vector = np.array([1,2,3])
print ("vector:",vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])

print("Matrix",matrix)

tensor = np.array([[[1,2],[1,2]],[[1,2],[3,4]]])

print("Tensor",tensor)

vector: [1 2 3]
Matrix [[1 2 3]
 [4 5 6]]
Tensor [[[1 2]
  [1 2]]

 [[1 2]
  [3 4]]]


### Array Properties

In [22]:
arr = np.array([[1,2,3],[4,5,"2.8"]])
print("Shape",arr.shape)
print("Dimension",arr.ndim)
print("Size",arr.size)
print("Dtype",arr.dtype)



Shape (2, 3)
Dimension 2
Size 6
Dtype <U21


### Array Reshaping

In [29]:
arr = np.arange(12)
print("Original array", arr)

reshaped = arr.reshape((3,4))
print("\n Reshaped Array",reshaped)

flattened = reshaped.flatten()
print("\n flattened Array",flattened)

#ravel (returns view, instead of copy)
ravelled = reshaped.ravel()
print("\n raveled array",ravelled)

# transpose

transpose = reshaped.T
print("\n Transposed Array",transpose)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
