In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X,y = load_iris(return_X_y= True)

In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
X_train, X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2)

In [7]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
import numpy as np 
((X_train -np.mean(X_train, axis = 0)) / np.std(X_train,axis = 0)) ## WHAT STANDARD SCALER DOES 

array([[ 1.56814814, -0.20151016,  1.24494789,  1.21423534],
       [-0.62421431,  1.38043879, -1.19775923, -1.22923913],
       [-1.11140596, -1.33147371,  0.4677229 ,  0.69981966],
       [-0.01522474,  2.05841692, -1.36430744, -1.22923913],
       [-1.11140596, -1.55746641, -0.19846995, -0.20040778],
       [ 0.350169  , -0.20151016,  0.68978718,  0.82842358],
       [-0.50241639,  0.70246067, -1.08672709, -1.22923913],
       [-1.23320388,  0.70246067, -0.97569494, -1.22923913],
       [ 0.59376483,  0.70246067,  1.07839968,  1.6000471 ],
       [ 0.350169  , -0.42750287,  0.57875504,  0.3140079 ],
       [-0.86781014,  0.47646796, -1.08672709, -0.84342737],
       [-0.38061848, -1.105481  ,  0.41220683,  0.05680006],
       [ 0.350169  , -1.105481  ,  1.07839968,  0.3140079 ],
       [ 0.95915857, -0.20151016,  0.41220683,  0.3140079 ],
       [ 1.08095649,  0.47646796,  1.13391575,  1.72865102],
       [-0.50241639,  1.83242421, -1.08672709, -0.97203129],
       [-0.86781014,  0.

In [10]:
X_train_scaled

array([[ 1.56814814, -0.20151016,  1.24494789,  1.21423534],
       [-0.62421431,  1.38043879, -1.19775923, -1.22923913],
       [-1.11140596, -1.33147371,  0.4677229 ,  0.69981966],
       [-0.01522474,  2.05841692, -1.36430744, -1.22923913],
       [-1.11140596, -1.55746641, -0.19846995, -0.20040778],
       [ 0.350169  , -0.20151016,  0.68978718,  0.82842358],
       [-0.50241639,  0.70246067, -1.08672709, -1.22923913],
       [-1.23320388,  0.70246067, -0.97569494, -1.22923913],
       [ 0.59376483,  0.70246067,  1.07839968,  1.6000471 ],
       [ 0.350169  , -0.42750287,  0.57875504,  0.3140079 ],
       [-0.86781014,  0.47646796, -1.08672709, -0.84342737],
       [-0.38061848, -1.105481  ,  0.41220683,  0.05680006],
       [ 0.350169  , -1.105481  ,  1.07839968,  0.3140079 ],
       [ 0.95915857, -0.20151016,  0.41220683,  0.3140079 ],
       [ 1.08095649,  0.47646796,  1.13391575,  1.72865102],
       [-0.50241639,  1.83242421, -1.08672709, -0.97203129],
       [-0.86781014,  0.

In [11]:
from sklearn.preprocessing import MinMaxScaler ## DATA BETWEEN 0N AND 1

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
X_train_scaled

array([[0.82352941, 0.41666667, 0.83050847, 0.83333333],
       [0.29411765, 0.70833333, 0.08474576, 0.04166667],
       [0.17647059, 0.20833333, 0.59322034, 0.66666667],
       [0.44117647, 0.83333333, 0.03389831, 0.04166667],
       [0.17647059, 0.16666667, 0.38983051, 0.375     ],
       [0.52941176, 0.41666667, 0.66101695, 0.70833333],
       [0.32352941, 0.58333333, 0.11864407, 0.04166667],
       [0.14705882, 0.58333333, 0.15254237, 0.04166667],
       [0.58823529, 0.58333333, 0.77966102, 0.95833333],
       [0.52941176, 0.375     , 0.62711864, 0.54166667],
       [0.23529412, 0.54166667, 0.11864407, 0.16666667],
       [0.35294118, 0.25      , 0.57627119, 0.45833333],
       [0.52941176, 0.25      , 0.77966102, 0.54166667],
       [0.67647059, 0.41666667, 0.57627119, 0.54166667],
       [0.70588235, 0.54166667, 0.79661017, 1.        ],
       [0.32352941, 0.79166667, 0.11864407, 0.125     ],
       [0.23529412, 0.625     , 0.06779661, 0.04166667],
       [0.17647059, 0.45833333,

In [16]:
X_min = np.min(X_train, axis= 0)
X_max = np.max(X_train, axis = 0)

(X_train - X_min) / (X_max - X_min)

array([[0.82352941, 0.41666667, 0.83050847, 0.83333333],
       [0.29411765, 0.70833333, 0.08474576, 0.04166667],
       [0.17647059, 0.20833333, 0.59322034, 0.66666667],
       [0.44117647, 0.83333333, 0.03389831, 0.04166667],
       [0.17647059, 0.16666667, 0.38983051, 0.375     ],
       [0.52941176, 0.41666667, 0.66101695, 0.70833333],
       [0.32352941, 0.58333333, 0.11864407, 0.04166667],
       [0.14705882, 0.58333333, 0.15254237, 0.04166667],
       [0.58823529, 0.58333333, 0.77966102, 0.95833333],
       [0.52941176, 0.375     , 0.62711864, 0.54166667],
       [0.23529412, 0.54166667, 0.11864407, 0.16666667],
       [0.35294118, 0.25      , 0.57627119, 0.45833333],
       [0.52941176, 0.25      , 0.77966102, 0.54166667],
       [0.67647059, 0.41666667, 0.57627119, 0.54166667],
       [0.70588235, 0.54166667, 0.79661017, 1.        ],
       [0.32352941, 0.79166667, 0.11864407, 0.125     ],
       [0.23529412, 0.625     , 0.06779661, 0.04166667],
       [0.17647059, 0.45833333,